config/routes.rb
Rails.application.routes.draw do

get   '/veggies' => 'veggies#find',  as: :veggies
get   '/veggies/:id' => "veggies#show"

get   '/fruits' => 'fruits#find',  as: :fruits

get   '/fruits/skipped' => 'fruits#skip',  as: :vegskip

get   '/herbs' => 'herbs#find',  as: :herbs

get   '/herbs/skipped' => 'herbs#skip',  as: :fruitskip

get   '/flowers' => 'flowers#find',  as: :flowers

get   '/flowers/skipped' => 'flowers#skip',  as: :herbskip

resources :users, :only => [:new, :create, :edit] do
    resources :plots

end

end

app/models/flower.rb
class Flower < ActiveRecord::Base
  belongs_to :plot
end

app/models/fruit.rb
class Fruit < ActiveRecord::Base
  belongs_to :plot
end

app/models/herb.rb
class Herb < ActiveRecord::Base
  belongs_to :plot
end

app/models/plot.rb
class Plot < ActiveRecord::Base
    belongs_to :user
    has_many :veggies
    has_many :fruits
    has_many :herbs
    has_many :flowers
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :plots
end

app/models/veggie.rb
class Veggie < ActiveRecord::Base
  belongs_to :plot
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::API
# Prevent CSRF attacks by raising an exception.
# For APIs, you may want to use :null_session instead.
# protect_from_forgery with: :exception
  end

app/controllers/flowers_controller.rb
class FlowersController < ApplicationController
  before_action :set_flower, only: [:show, :edit, :update, :destroy]

# this doesnt have a route
  def index
    @flowers = Flowers.all

  end

  #herbs is an *array* of the herb types the user picked and sent over
  def find
    @fruits = params[:fruits].split(',')
    @veggies = params[:veggies].split(',')
    @herbs = params[:herbs].split(',')

    @flowers = [ ]
    @herbs.each do |herb|
      @flowers += Flower.where("companions like ?", "%#{herb}%")
    end

    @fruits.each do |fruit|
      @flowers += Flower.where("companions like ?", "%#{fruit}%")
    end

    @veggies.each do |veggie|
      @flowers += Flower.where("companions like ?", "%#{veggie}%")
    end


    @flowers.uniq

    render json: @flowers
  end

    def skip
      @soil = params[:soil]
      @zone = params[:zone]

      @flowers = Flower.where("soil like ?", "%#{@soil}%").where("hardinessZone like?", "%#{@zone}%")

      render json: @flowers

    end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flower
      @flower = Flower.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def flower_params
      params.require(:flower).permit(:name, :soil, :space, :hardinessZone, :sunShine, :start, :special, :companions, :foes)
    end
end

app/controllers/fruits_controller.rb
class FruitsController < ApplicationController
  before_action :set_fruit, only: [:show, :edit, :update, :destroy]

# this doesnt have a route
  def index
    @fruits = Fruits.all

  end

  #veggies is an *array* of the veggie types the user picked and sent over
  def find
    @veggies = params[:veggies].split(',')


    @fruits = [ ]
    @veggies.each do |veggie|
      @fruits += Fruit.where("companions like ?", "%#{veggie}%")
    end

    @fruits.uniq!

    render json: @fruits
    # ***WHAT IF THERE ARE NO MATCHES?****


  end



  def skip
    @soil = params[:soil]
    @zone = params[:zone]

    @fruits = Fruit.where("soil like ?", "%#{@soil}%").where("hardinessZone like?", "%#{@zone}%")

  render json: @fruits

  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fruit
      @fruit = Fruit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fruit_params
      params.require(:fruit).permit(:name, :soil, :space, :hardinessZzone, :sunShine, :start, :special, :companions, :foes)
    end
end

app/controllers/herbs_controller.rb
class HerbsController < ApplicationController
  before_action :set_herb, only: [:show, :edit, :update, :destroy]

# this doesnt have a route
  def index
    @herbs = Herbs.all

  end

  #fruits is an *array* of the fruit types the user picked and sent over
  def find
    @fruits = params[:fruits].split(',')
    @veggies = params[:veggies].split(',')


    @herbs = [ ]
    @fruits.each do |fruit|
      @herbs += Herb.where("companions like ?", "%#{fruit}%")
    end

    @veggies.each do |veggie|
      @herbs += Herb.where("companions like ?", "%#{veggie}%")
    end


    @herbs.uniq!

    render json: @herbs

    # ***WHAT IF THERE ARE NO MATCHES?

  end



  def skip
    @soil = params[:soil]
    @zone = params[:zone]

    @herbs = Herb.where("soil like ?", "%#{@soil}%").where("hardinessZone like?", "%#{@zone}%")

  render json: @herbs

  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_herb
      @herb = Herb.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def herb_params
      params.require(:herb).permit(:name, :soil, :space, :hardinessZone, :sunShine, :start, :special, :companions, :foes)
    end
end

app/controllers/plots_controller.rb
class PlotsController < ApplicationController
  def new
    @plot = Plot.new
  end

  def create
    @plot = Plot.new(user_create_params[:plot])
  end


  private

  def plot_create_params
    params.permit(plot: [:user_id, :width, :length])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_create_params[:user])
  end


  private

  def user_create_params
    params.permit(user: [:username, :email, :password, :password_confirmation])
  end
end


# Gotta send user info over url? The password digest thing is a thing, but idk....oauth is better? idk

app/controllers/veggies_controller.rb
class VeggiesController < ApplicationController
  # before_action :set_veggie, only: [:show, :edit, :update, :destroy]

  # for companions, return as an array?
  # alphbetize companions
  # make sure to downcase everything

  # this doesnt have a route
  def index
    @veggies = Veggies.all

  end

  def find
    @soil = params[:soil]
    @zone = params[:zone]

# localhost:3000/veggies?soil=loamy&zone=9
    # @soil = params[:soil]

    @veggies = Veggie.where("soil like ?", "%#{@soil}%").where("hardinessZone like?", "%#{@zone}%")

# veggies = Veggie.where("soil like ?", "%loamy%").where("hardinessZone like?", "%10%")
# Veggie.where("soil like ?", soil).where("hardinessZone like?", "%10%") <= this returns veggies with ONLY loamy as their soil type

# the info comes back from the active record query as an array of hashes, sooooo....
  # render json: {data: {type: 'veggie', attributes: @veggies}}
  render json: {veggies: @veggies}

  # id???

  end

  def show
    @id = params[:id]

    @veggy = Veggie.where("id like ?", "%#{@id}")

    render json: {veggy: @veggy}
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_veggie
      @veggie = Veggie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def veggie_params
      params.require(:veggie).permit(:name, :soil, :space, :hardinesszone, :sunShine, :start, :special, :companions, :foes)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PlantApi</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/plants/_form.html.erb
<%= form_for(@plant) do |f| %>
  <% if @plant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@plant.errors.count, "error") %> prohibited this plant from being saved:</h2>

      <ul>
      <% @plant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :soil %><br>
    <%= f.text_field :soil %>
  </div>
  <div class="field">
    <%= f.label :space %><br>
    <%= f.number_field :space %>
  </div>
  <div class="field">
    <%= f.label :hardinessZone %><br>
    <%= f.text_field :hardinessZone %>
  </div>
  <div class="field">
    <%= f.label :sunShine %><br>
    <%= f.number_field :sunShine %>
  </div>
  <div class="field">
    <%= f.label :start %><br>
    <%= f.number_field :start %>
  </div>
  <div class="field">
    <%= f.label :special %><br>
    <%= f.number_field :special %>
  </div>
  <div class="field">
    <%= f.label :companions %><br>
    <%= f.text_field :companions %>
  </div>
  <div class="field">
    <%= f.label :foes %><br>
    <%= f.number_field :foes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/veggies/_form.html.erb
<%= form_for(@veggie) do |f| %>
  <% if @veggie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@veggie.errors.count, "error") %> prohibited this veggie from being saved:</h2>

      <ul>
      <% @veggie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :soil %><br>
    <%= f.text_field :soil %>
  </div>
  <div class="field">
    <%= f.label :space %><br>
    <%= f.number_field :space %>
  </div>
  <div class="field">
    <%= f.label :hardinessZone %><br>
    <%= f.text_field :hardinessZone %>
  </div>
  <div class="field">
    <%= f.label :sunShine %><br>
    <%= f.number_field :sunShine %>
  </div>
  <div class="field">
    <%= f.label :start %><br>
    <%= f.number_field :start %>
  </div>
  <div class="field">
    <%= f.label :special %><br>
    <%= f.number_field :special %>
  </div>
  <div class="field">
    <%= f.label :companions %><br>
    <%= f.text_field :companions %>
  </div>
  <div class="field">
    <%= f.label :foes %><br>
    <%= f.number_field :foes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/veggies/edit.html.erb
<h1>Editing Veggie</h1>

<%= render 'form' %>

<%= link_to 'Show', @veggie %> |
<%= link_to 'Back', veggies_path %>

app/views/veggies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Veggies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Soil</th>
      <th>Space</th>
      <th>Hardiness Zones</th>
      <th>Sun</th>
      <th>Start</th>
      <th>Special</th>
      <th>Companions</th>
      <th>Foes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @veggies.each do |veggie| %>
      <tr>
        <td><%= veggie.name %></td>
        <td><%= veggie.soil %></td>
        <td><%= veggie.space %></td>
        <td><%= veggie.hardinessZone %></td>
        <td><%= veggie.sunShine %></td>
        <td><%= veggie.start %></td>
        <td><%= veggie.special %></td>
        <td><%= veggie.companions %></td>
        <td><%= veggie.foes %></td>
        <td><%= link_to 'Show', veggie %></td>
        <td><%= link_to 'Edit', edit_veggie_path(veggie) %></td>
        <td><%= link_to 'Destroy', veggie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Veggie', new_veggie_path %>

app/views/veggies/new.html.erb
<h1>New Veggie</h1>

<%= render 'form' %>

<%= link_to 'Back', veggies_path %>

app/views/veggies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @veggie.name %>
</p>

<p>
  <strong>Soil:</strong>
  <%= @veggie.soil %>
</p>

<p>
  <strong>Space:</strong>
  <%= @veggie.space %>
</p>

<p>
  <strong>Hardiness Zone:</strong>
  <%= @veggie.hardinessZone %>
</p>

<p>
  <strong>Sun:</strong>
  <%= @veggie.sunShine %>
</p>

<p>
  <strong>Start:</strong>
  <%= @veggie.start %>
</p>

<p>
  <strong>Special:</strong>
  <%= @veggie.special %>
</p>

<p>
  <strong>Companions:</strong>
  <%= @veggie.companions %>
</p>

<p>
  <strong>Foes:</strong>
  <%= @veggie.foes %>
</p>

<%= link_to 'Edit', edit_veggie_path(@veggie) %> |
<%= link_to 'Back', veggies_path %>